language: node_js
node_js:
- '8'
sudo: required
services: 
script: 
deploy:
  provider: script
  script: "./travis-release-script"
  on:
    branch: master
env:
  global:
    secure: auPqO89RladAX2IyYLmW0l4sJxAyPVMfLveBUN+M7e+lGAtaK4hvjUDEqp8sk5GhiT5YX2GnX8O6ZlBxoae1+wE0kv8fpJv4ZoFK89Mv6JCV83xEWsUlDhX2a1OvdoPuqHmpQTE2VTzQqWCEusQ6do8NxA4w56xGfL0piZeRQj2uuPRa7NZfVCzruNPWjLl3ixg1flzbFSkC8wMPzTMI8Ku9ZUx/ZeedptKG5I4dl3ygEd8VWtv74mla5DDn+3d0HMu5l+qaKdr8E8+0/Mpg9tpHGpXY6lfN7n9m2mmJv9f9l9HzX7IC6jp5GFr8rsJQYWdRd8Dm01/hj19EUzziCfm7Nf7FrMXv696twGimOo0z2NSAoOfES255X2KeLSeoxZM3TSrqEJSWvYe7wvnYclP+jdnY7UbQ00NZUrACWmUkyFzAQ9XN6sVumOE0RpPxMHEYJg6ivd81+Caifcs1y31JHCDE/tAB6xLzXGWchHjQqlFvEo6FdRXpintwoz1kdLkR8qECCHPwFF85n1CM6GfJXnengxBUjmGujBbh3itnu98d545NotQkeLkTusjBjgBzMUodX2iM+zjSCr4TNNFgWZ17G4yUrPEWoGJIq1vs8e1Uuf/1RYUWXozGBMuXv7TorI47Ak5lfrqzhlXQpuHgB38Gw8/1DR/NznUCN+4=
