language: node_js
node_js:
- '8'
sudo: required
services: 
script: 
deploy:
  provider: script
  script: "./travis-release-script"
  on:
    branch: master
env:
  global:
    secure: HET652A0D0zWl7Xej5fmQEspqJ4b30yy5xlpMgItJLBf7/Zo2qzGG5TAP/va/KPuQbju9ml3HBqGHYhBfoVxEoSgPnwkJUG4i1tw4uTIf3tGfqcHUzuQjRzsedjViJNxyPsSaQyFJFUDR+mN7hzuY11rRlMGLEr9343TnXFe80FkqI/W4cYywn8e4CJ3oFi23Zu/Y+Ynpcc3XeYrofUfkyDLQQRn/kM6KbWfNfAa4NhkPtYeruZkr4AZXL+Te/4ZFYYM+x152mRkCYtg9Z6uVccgDu4Fm9hZ85R68pJsh/smWzw3fgnFvIw3uJzzo6jHjsambUNMHTZOSWW8cxgjNK3aqKFEmtv4/MwsZRXssdyWBywfn0BeOBsPFs+eqFNpKiD2PNx7W8aEqUMQgmboqkWq5sLP0Ks/Lmlsk4/LzuKzfS6DPaz3gU5JxBwjWA3d2hA1QnQWRv67vXeTv9Cw+vFTA03wLDUYLggrgwsaByzMUqrJY1Ud7LPHIYppvPZojksl5ZHGoN++21iIg3YXzy5lXPmgflwGP/qWUtDOujmfzi00SHJPXam6MDVOAweNG595vQW8C1C8Y2i55HlyC5udn7/C8zHsDVTermsSWYj96sahrN8Pa5nS3ap90yRxwVL1RbHLYmrZJHVfEAKpaMniYsFcfPQOfaFWTzWcFc8=
