language: node_js
node_js:
- '8'
sudo: required
services: 
script: 
deploy:
  provider: script
  script: "./travis-release-script"
  on:
    branch: master
env:
  global:
    secure: hZ/sm+x7yqVFJDdfOMT1TIWOxnODIbAdeZS/chxZI/8rFu95eSSWHlFtwRB0tRwDQbtIrELkz/OALZATAkIrtXDVs3fkKpEOmmbJ/3YCpESulStYdU91LqkWds9+rwIyKkpryVEdO/gDC5QYHk9z/wMKYdvbAo5iaA52z7gqRGRML2QMW+URWY/nhfN7Iu3zMOdmFQpbj+a1v5B57YdIupp326jkvAQ4BHej3qZGID6nTeFqI7ZSHcu1DJO9Izx6qd3BCHWZltj1uI7Q0HDHjcH9uz7ZfIU+6fu+bP8/VrvSeMtODreiKKGih3OLkhvZ/lO/u1e8aMnW4ErjswNbTXJ+15LPpMFCEFs4mcC9rf6nAjO2Iai3wTufMBNJvsGRRZZLNudRFlZ+IVynqKSTigIXexwegu7jA0m864zfiRXc27mUy7Ww7vUJDvcZtCS2ntkvRJ2mQzBK48JwlabIHjXTO6D6yJ69wV5zqiFJ+iBzzh8O26dJXD+4LGdfxBIC/Br3jItsg9xHUgYLJYnZw7baMBI1zK6zodrvvWlxZMr2pjiBDNfTs/sAprFfVz5HpiADTkNJkszUs3MaZh0wHtJkzVIM7Ds0gGs8yY6ljWqA+DsFCr8nlhI1OLZN5t6eZQL7hjihbnjjUW31VfHGHW6scun6/BzGQZfR7LbKHQE=
