language: node_js
node_js:
- '8'
sudo: required
services: 
script: 
deploy:
  provider: script
  script: "./travis-release-script"
  on:
    branch: master
env:
  global:
    secure: eSxHv67Z7Vw5kIzKCln2lNrUKB3Jz2atn3+TcCKW3y5X6LBUxAMunbSBNFPwruSrMCxOZhvnB3kYZSQ4d4gHl0ulepd6OoxxXEAmIG/UHj35nnEM9r7u9vbglqydMxu3qH4Be9KXMNHJMioGF3TpkL4ahcTfY5CpxB75/kWCjhttJtAT0Ptx+GTX7JS6CFUmuflLt3mMIM2eUr3KuGTZNNLg8w9Q+ApoAROLucA8xozpuHNEyUB9osMNMHMM+JdUFKMYdCV2qah5MeQ68R1oPOWcWz53MWElQ+qGQoKzoPLwkHfPo54fJoXVwOQrHSAsYiN7aPa7lhDtPFh0oXCD3URCSZO8UrO0I0q+YX0fUWQ83JgjJy9R99hMxSzDO94G5QbHER78TnHdHyL9U8R0ecuP4cQ0jawDw56erufRA61lBHq+TwigR1KZmMgtxZtvS71raG8j8ZojdaGiN+ll5iXCFBFhEzkfzDaJHIVoJ8PQZMIJvFZ/X56VdRaqO6957T1fXCYAUsddD/d/6aHwOPle7J9pmgbqbjs5H0Ut77cVk9cosP/hGRPAb5duN8GdsYdiG0qim62YW0vzMwl7bzX+CczqbsTQu8JoNnrU/x0kdPDqEAZAz+hfwx/4ZDpBR42FkLAV5wFvLWPVaBSdjZwN7OBvzPM/O/sPGAxEUXQ=
