#!/usr/bin/env bash
git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"

git checkout $TRAVIS_BRANCH

echo Travis Branch is $TRAVIS_BRANCH

git remote set-url --push origin https://${GH_TOKEN}@github.com/poeatlas/atlas-ui.git

./node_modules/release-it/bin/release.js patch --non-interactive
